# Generated by Django 3.2.17 on 2023-02-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.CharField(default='2023-02-05', max_length=10, unique=True),
        ),
    ]
