# Generated by Django 3.2.17 on 2023-02-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230205_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.CharField(default='2023-02-05', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('date', 'user')},
        ),
    ]
